version: "3"

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    restart: always
    container_name: api
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "5050:5050"
    volumes:
      - ./api:/app
    links:
      - postgres
    command: ["flask", "run", "--host=0.0.0.0", "--port=5050"]

volumes:
  postgres_data:

